# Generated by Django 4.0.3 on 2022-03-29 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdoption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('castrated', models.BooleanField()),
                ('is_vaccinated', models.BooleanField()),
                ('is_health', models.BooleanField()),
                ('additional_info', models.TextField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('adopted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
