# Generated by Django 4.0.3 on 2022-03-24 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Pet sitter', 'Pet sitter'), ('Pet walker', 'Pet walker'), ('Pet trainer', 'Pet trainer'), ('Pet taxi', 'Pet taxi')], max_length=11)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
