# Generated by Django 4.0.3 on 2022-03-23 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PS', 'Pet sitter'), ('PW', 'Pet walker'), ('PTR', 'Pet trainer'), ('PTX', 'Pet taxi')], max_length=3)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
