# Generated by Django 4.0.3 on 2022-03-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('orders', '0001_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratings.rating'),
        ),
    ]
