# Generated by Django 4.0.3 on 2022-03-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
        ('orders', '0002_order_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.pet'),
        ),
    ]
